IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'DESKTOP-833QAHA\sql01')
CREATE LOGIN [DESKTOP-833QAHA\sql01] FROM WINDOWS
GO
CREATE USER [sql01] FOR LOGIN [DESKTOP-833QAHA\sql01]
GO
